'use client';
import {useState} from 'react';
const companies=[
 ['أراك للتنمية','ARAAK DEVELOPMENT','نبني القدرة المؤسسية ونحوّل التحديات إلى برامج ومشروعات قابلة للتنفيذ.','التنمية والاستشارات'],
 ['أراك الصناعية','ARAAK INDUSTRY','قدرات صناعية وحلول إنتاجية تربط الجودة بالكفاءة وسلاسل القيمة.','الصناعة والحلول'],
 ['أراك التجارية','ARAAK TRADING','تجارة وتوريد وتطوير فرص تربط الأسواق بالمشروعات والاحتياج الحقيقي.','التجارة والتوريد'],
 ['أراك ستورز','ARAAK STORES','واجهة تجارية رقمية لمنتجات مختارة وتجربة شراء تتطور مع منظومة المجموعة.','التجزئة والتجارة الإلكترونية'],
 ['أراك الأكاديمية','ARAAK ACADEMY','معرفة تطبيقية وبناء قدرات وبرامج تطوير تستثمر في الإنسان والمؤسسة.','المعرفة وبناء القدرات'],
 ['أراك اللوجستية','ARAAK LOGISTICS','حلول لوجستية وسلاسل إمداد تدعم حركة الأعمال من المصدر إلى الوجهة.','اللوجستيات وسلاسل الإمداد']
];
const insights=['قصاصات أراك','التقارير والدراسات','دراسات الحالة','الأخبار والمنشورات'];
export default function Home(){const [sent,setSent]=useState(false); async function submit(e){e.preventDefault(); const f=new FormData(e.currentTarget); await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))}); setSent(true); e.currentTarget.reset();}
return <main>
<header className="nav"><a className="brand" href="#top"><b>أراك</b><span>ARAAK HOLDING</span></a><nav><a href="#group">المجموعة</a><a href="#ecosystem">منظومتنا</a><a href="#projects">المشاريع</a><a href="#insights">المعرفة</a><a href="#governance">الحوكمة</a></nav><a className="pill" href="#contact">تواصل معنا</a></header>
<section id="top" className="hero"><img src="/araak-hero.jpg" alt="مشهد سينمائي يجمع المدينة والصناعة واللوجستيات"/><div className="veil"/><div className="heroCopy"><span className="eyebrow">ARAAK HOLDING · مجموعة أراك القابضة</span><h1>قيمةٌ تتسع<br/>إلى <em>منظومة.</em></h1><p>نبني ونمكّن منظومات أعمال تجمع التنمية والمعرفة والصناعة والتجارة والخدمات في قيمة مستدامة.</p><div><a className="primary" href="#ecosystem">استكشف المنظومة</a><a className="ghost" href="#group">قصة أراك</a></div></div><div className="scroll">اكتشف أراك ↓</div></section>
<section id="group" className="statement"><span>منذ البدايات وحتى اليوم</span><h2>بدأنا بالتنمية.<br/>واتسعت التجربة إلى <i>منظومة أعمال.</i></h2><p>أراك القابضة هي المظلة الاستراتيجية لشركات وقطاعات تتشارك فلسفة واحدة: توطين القيمة، بناء القدرة، وتحويل الفرص إلى أثر اقتصادي وتنموي قابل للاستمرار.</p></section>
<section id="ecosystem" className="section"><div className="sectionHead"><div><span>01 · OUR ECOSYSTEM</span><h2>منظومة أراك</h2></div><p>هويات متخصصة، تعمل باستقلال تشغيلي وتتشارك الرؤية والحوكمة والقدرات.</p></div><div className="grid">{companies.map((c,i)=><article className="card" key={c[1]}><small>0{i+1}</small><div className="tag">{c[3]}</div><h3>{c[0]}</h3><b>{c[1]}</b><p>{c[2]}</p><a href="#contact">استكشف القطاع ←</a></article>)}</div></section>
<section className="numbers"><div><strong>2008</strong><span>بداية الرحلة</span></div><div><strong>+53</strong><span>دولة في امتداد الخبرة</span></div><div><strong>06</strong><span>قطاعات أعمال مترابطة</span></div><div><strong>∞</strong><span>قيمة قابلة للنمو</span></div></section>
<section id="projects" className="section dark"><div className="sectionHead"><div><span>02 · FLAGSHIP PROJECTS</span><h2>من التحدي إلى الأثر</h2></div><p>نعرض المشاريع كدراسات حالة: التحدي، تدخل أراك، الحل، والنتيجة.</p></div><div className="projects"><article><span>التنمية المؤسسية</span><h3>بناء المنظومات والجاهزية التشغيلية</h3><p>تصميم نماذج تشغيل وحوكمة وقدرات تحول الفكرة إلى مؤسسة قابلة للنمو.</p></article><article><span>الصناعة</span><h3>رفع القدرة الإنتاجية</h3><p>تطوير العمليات وربط الإنتاج بالجودة والطلب وسلسلة الإمداد.</p></article><article><span>الشراكات</span><h3>من العلاقة إلى قيمة مشتركة</h3><p>تحويل شبكات العلاقات إلى فرص ومشاريع وشراكات قابلة للقياس.</p></article></div></section>
<section className="world"><div><span>03 · GLOBAL FOOTPRINT</span><h2>أراك حول العالم</h2><p>خبرة تتحرك عبر الأسواق، وتتكيف مع السياق، وتحافظ على جوهر واحد.</p></div><div className="orb"><b>ARAAK</b><span>Saudi Arabia · Egypt · Sudan · Côte d’Ivoire · Japan · Maldives · India</span></div></section>
<section id="insights" className="section"><div className="sectionHead"><div><span>04 · ARAAK INSIGHTS</span><h2>المعرفة التي نصنعها من الممارسة</h2></div><p>ليس أرشيف أخبار؛ بل ذاكرة فكرية للمجموعة وما تتعلمه من السوق والمشروعات.</p></div><div className="insights">{insights.map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3><b>→</b></div>)}</div></section>
<section className="journey"><span>05 · OUR JOURNEY</span><h2>2008 <i>→</i> 2026 <i>→</i> Beyond</h2><p>من مبادرات التنمية، إلى بناء القدرات، إلى الصناعة والتجارة والمنصات والخدمات؛ الرحلة مستمرة، لكن البوصلة واحدة.</p></section>
<section id="governance" className="section governance"><div><span>06 · GOVERNANCE</span><h2>نموٌ تحرسه الحوكمة.</h2><p>فصل واضح بين الملكية والإدارة والتشغيل، مع حوكمة للمجموعة وصلاحيات للشركات التابعة ومركز خدمات مشتركة يرفع الكفاءة دون أن يلغي استقلالها.</p></div><div className="govgrid"><b>مجلس الإدارة</b><b>قيادة المجموعة</b><b>الاستراتيجية والأداء</b><b>المالية والاستثمار</b><b>الحوكمة والالتزام</b><b>الخدمات المشتركة</b></div></section>
<section id="contact" className="contact"><div><span>07 · PARTNERSHIPS</span><h2>لنبدأ من<br/>الفرصة.</h2><p>استثمار، شراكة، مشروع، أو فرصة تحتاج إلى قدرة متعددة التخصصات.</p></div><form onSubmit={submit}><input name="name" required placeholder="الاسم"/><input name="email" type="email" required placeholder="البريد الإلكتروني"/><select name="interest" defaultValue=""><option value="" disabled>مجال التواصل</option><option>استثمار وشراكات</option><option>مشروع أو خدمة</option><option>إعلام وتواصل</option></select><textarea name="message" required placeholder="حدثنا عن الفرصة"/><button>{sent?'تم الاستلام ✓':'إرسال الرسالة'}</button></form></section>
<footer><div className="brand"><b>أراك</b><span>ARAAK HOLDING</span></div><p>نحو توطين القيم لتمكين التنمية.</p><div>© 2026 ARAAK HOLDING · نموذج أولي</div></footer>
</main>}