'use client';
import {useState} from 'react';
const business=[
['01','الصناعة','MANUFACTURING','مصنع أراك للحديد','تصنيع قطاعات وصفائح الصلب المجلفن، واللفائف وقواطع الحوائط الجافة وإكسسوارات الأسقف الفولاذية، إلى جانب مركز خدمة الصلب.','https://araak.net/أراك-مصنع-أراك-للحديد/'],
['02','التجارة','BUILDING MATERIALS','مواد البناء والديكور والعوازل','توريد مواد بناء عالية الجودة للمقاولين وتجار الجملة والتجزئة وأصحاب المشاريع.','https://araak.net/التجارة-الديكور-ومواد-البناء/'],
['03','المقاولات','PROJECTS & CONTRACTING','المشاريع والبناء','تنفيذ وتوريد وحلول تعاقد متخصصة للمشاريع السكنية والتنموية، مدعومة بخبرات المواد وإدارة مواقع العمل.','https://araak.net/'],
['04','التنمية','DEVELOPMENT','التعليم · التدريب · الاستشارات','برامج ومبادرات واستشارات لبناء القدرات المؤسسية والبشرية منذ انطلاقة أراك.','https://www.araak.org/home/'],
['05','التعليم الرقمي','ARAAK ACADEMY','أكاديمية أراك','منصة تعليمية تفاعلية للدورات والبرامج، بمحتوى مسجل وبث مباشر وأدوات قياس وتمكين.','https://academy.araak.org/']];
const products=[['ألواح الجبس','GYPSUM BOARDS'],['الديكور','DECORATIVE SOLUTIONS'],['أسقف الألياف المعدنية','MINERAL FIBER CEILINGS'],['العزل الحراري','THERMAL INSULATION']];
const projects=['عالم واحد','بيت الخبرة للخدمات الاستشارية','البناء الموسوعي','إدراك · صناعة الداعية','وفود · تأهيل المؤثرين','عطاء · تطوير القطاع الثالث','رشد · صناعة القادة','مراقي · إعداد المدربين','غراس · الميول والتخصص','معين · القيادات التربوية'];
export default function Home(){const[sent,setSent]=useState(false);async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});setSent(true);e.currentTarget.reset()}return <main>
<header className="nav"><a className="brand" href="#top"><b>أراك</b><span>ARAAK GROUP</span></a><nav><a href="#business">أعمالنا</a><a href="#products">المنتجات</a><a href="#development">التنمية</a><a href="#academy">الأكاديمية</a><a href="#group">المجموعة</a></nav><a className="cta" href="#contact">تواصل معنا</a></header>
<section id="top" className="hero"><div className="heroImage"/><div className="veil"/><div className="heroCopy"><span>ARAAK GROUP · مجموعة أراك</span><h1>قدرات صناعية.<br/><em>حلول تجارية.</em><br/>مشاريع فعلية.</h1><p>أعمال متكاملة في الصناعة ومواد البناء والمقاولات والتنمية والتعليم — تجمعها خبرة أراك وتدفعها قيمة واحدة.</p><div><a className="cta" href="#business">استكشف أعمال أراك</a><a className="ghost" href="#products">تصفح المنتجات</a></div></div><div className="rail">INDUSTRY · TRADE · PROJECTS · DEVELOPMENT · ACADEMY</div></section>
<section className="proof"><div><b>2008</b><span>انطلاقة أراك للتنمية</span></div><div><b>+53</b><span>دولة في شبكة أراك</span></div><div><b>3</b><span>مجالات لأراك التجارية</span></div><div><b>26</b><span>نتيجة تدريبية بالأكاديمية</span></div></section>
<section id="business" className="section"><header className="sectionHead"><div><span>01 · WHAT WE DO TODAY</span><h2>أعمال أراك اليوم</h2></div><p>قطاعات تشغيل قائمة تخدم السوق عبر التصنيع والتوريد والمقاولات والتنمية والتعليم.</p></header><div className="business">{business.map((x,i)=><article key={x[0]}><div className={'visual v'+i}><small>{x[2]}</small></div><div className="copy"><span>{x[0]} · {x[1]}</span><h3>{x[3]}</h3><p>{x[4]}</p><a href={x[5]} target="_blank">الدخول إلى النشاط ↗</a></div></article>)}</div></section>
<section id="products" className="products section"><header className="sectionHead"><div><span>02 · PRODUCTS</span><h2>توريد متكامل<br/>لمتطلبات المشاريع.</h2></div><p>حلول مواد البناء والديكور والعوازل التي تعرضها أراك التجارية لعملائها.</p></header><div className="productGrid">{products.map((p,i)=><article key={p[0]}><div className={'art a'+i}><i>0{i+1}</i></div><span>{p[1]}</span><h3>{p[0]}</h3><a href="https://araak.net/" target="_blank">التفاصيل ↗</a></article>)}</div></section>
<section className="factory"><div className="factoryArt"><i/><i/></div><div><span>03 · ARAAK STEEL FACTORY</span><h2>صناعةٌ تدخل<br/>في صميم البناء.</h2><p>مصنع أراك للحديد متخصص في تصنيع قطاعات الصلب والصفائح واللفائف وقواطع الحوائط الجافة وإكسسوارات الأسقف الفولاذية، مع مركز لخدمة الصلب.</p><div className="chips"><b>Galvanized Steel</b><b>Drywall Profiles</b><b>Ceiling Accessories</b><b>Steel Service Center</b></div><a href="https://araak.net/أراك-مصنع-أراك-للحديد/" target="_blank">اكتشف المصنع ↗</a></div></section>
<section id="development" className="section"><header className="sectionHead"><div><span>04 · ARAAK DEVELOPMENT</span><h2>خبرة بدأت بالإنسان.</h2></div><p>التعليم والتدريب والاستشارات هي الجذور التي انطلقت منها أراك، ومنها تشكل رصيد من البرامج والمبادرات وبناء القدرات.</p></header><div className="dev"><div><h3>نبني القدرة،<br/>ثم نتركها تعمل.</h3><p>تقييم القدرات المؤسسية، التخطيط الاستراتيجي، الأطر التشغيلية، الجودة والتحسين، دراسات الجدوى وتمكين رواد الأعمال.</p><a href="https://www.araak.org/home/" target="_blank">زيارة أراك للتنمية ↗</a></div><div className="projectList">{projects.map((x,i)=><p key={x}><b>0{i+1}</b>{x}</p>)}</div></div></section>
<section id="academy" className="academy"><div><span>05 · ARAAK ACADEMY</span><h2>المعرفة<br/>كمنتجٍ قابل للنمو.</h2><p>منصة تعليمية تفاعلية تقدم دورات وبرامج تدريبية بمستويات متعددة، مع مواد مسجلة وبث مباشر وأدوات للقياس والتمكين.</p><div className="stats"><b>26 <small>نتيجة بالدورات</small></b><b>20 <small>دورة تدريبية</small></b></div><a href="https://academy.araak.org/" target="_blank">الدخول إلى الأكاديمية ↗</a></div><div className="courses"><small>نماذج من المحتوى الحالي</small>{['الإدارة الذكية للموارد البشرية','إدارة الجودة الشاملة','التخطيط الإداري','بناء فريق العمل','إدارة التغيير','مراقي الحرمين · تدريب المدربين'].map(x=><h3 key={x}>{x}</h3>)}</div></section>
<section id="group" className="section group"><header className="sectionHead"><div><span>06 · THE GROUP</span><h2>أراك ليست نشاطًا واحدًا.</h2></div><p>نجمع واجهات الأعمال القائمة تحت مظلة واحدة، مع إبقاء كل نشاط قريبًا من سوقه وعملائه.</p></header><div className="groupGrid"><a href="https://araak.net/" target="_blank"><b>أراك التجارية</b><span>صناعة · تجارة · مقاولات</span></a><a href="https://www.araak.org/home/" target="_blank"><b>أراك للتنمية</b><span>تعليم · تدريب · استشارات</span></a><a href="https://academy.araak.org/" target="_blank"><b>أكاديمية أراك</b><span>تعليم وتدريب إلكتروني</span></a><div><b>أراك ستورز</b><span>التجارة والمتاجر</span></div></div></section>
<section className="footprint"><div><span>07 · FOOTPRINT</span><h2>حضور محلي.<br/>شبكة دولية.</h2><p>تصف أراك مجتمعها بأنه يضم شركاء ومدربين ومتدربين ومتعاملين في أكثر من 53 دولة.</p></div><div className="world"><b>JEDDAH</b><span>53+ COUNTRIES NETWORK</span></div></section>
<section id="contact" className="contact"><div><span>08 · BUSINESS ENQUIRIES</span><h2>ماذا تحتاج<br/>من أراك؟</h2><p>منتجات وتوريد ومشاريع وتدريب واستشارات وشراكات عبر نقطة اتصال موحدة.</p></div><form onSubmit={submit}><input name="name" required placeholder="الاسم / الجهة"/><input name="email" type="email" required placeholder="البريد الإلكتروني"/><select name="interest" defaultValue=""><option value="" disabled>اختر نوع الاحتياج</option><option>منتجات ومواد بناء</option><option>مصنع أراك للحديد</option><option>مقاولات ومشاريع</option><option>تدريب وتعليم</option><option>استشارات وتنمية</option><option>شراكة</option></select><textarea name="message" required placeholder="صف احتياجك باختصار"/><button>{sent?'تم استلام طلبك ✓':'إرسال الطلب'}</button></form></section>
<footer><a className="brand" href="#top"><b>أراك</b><span>ARAAK GROUP</span></a><p>نحو توطين القيم لتمكين التنمية.</p></footer>
</main>}