'use client';
import {useState} from 'react';
const business=[
['01','الصناعة','MANUFACTURING','مصنع اراك للحديد','تصنيع قطاعات وصفائح الصلب المجلفن، واللفائف وقواطع الحوائط الجافة وإكسسوارات الأسقف الفولاذية، إلى جانب مركز خدمة الصلب.','https://araak.net/اراك-مصنع-اراك-للحديد/'],
['02','التجارة','BUILDING MATERIALS','مواد البناء والديكور والعوازل','توريد مواد بناء عالية الجودة للمقاولين وتجار الجملة والتجزئة وأصحاب المشاريع.','https://araak.net/التجارة-الديكور-ومواد-البناء/'],
['03','المقاولات','PROJECTS & CONTRACTING','المشاريع والبناء','تنفيذ وتوريد وحلول تعاقد متخصصة للمشاريع السكنية والتنموية، مدعومة بخبرات المواد وإدارة مواقع العمل.','https://araak.net/'],
['04','التنمية','DEVELOPMENT','التعليم · التدريب · الاستشارات','برامج ومبادرات واستشارات لبناء القدرات المؤسسية والبشرية منذ انطلاقة اراك.','https://www.araak.org/home/'],
['05','التعليم الرقمي','ARAAK ACADEMY','أكاديمية اراك','منصة تعليمية تفاعلية للدورات والبرامج، بمحتوى مسجل وبث مباشر وأدوات قياس وتمكين.','https://academy.araak.org/']];
const products=[['ألواح الجبس','GYPSUM BOARDS'],['الديكور','DECORATIVE SOLUTIONS'],['أسقف الألياف المعدنية','MINERAL FIBER CEILINGS'],['العزل الحراري','THERMAL INSULATION']];
const projects=['عالم واحد','بيت الخبرة للخدمات الاستشارية','البناء الموسوعي','إدراك · صناعة الداعية','وفود · تأهيل المؤثرين','عطاء · تطوير القطاع الثالث','رشد · صناعة القادة','مراقي · إعداد المدربين','غراس · الميول والتخصص','معين · القيادات التربوية'];
export default function Home(){const[sent,setSent]=useState(false);async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});setSent(true);e.currentTarget.reset()}return <main>
<header className="nav"><a className="brand" href="#top"><b>اراك القابضة</b><span>ARAAK HOLDING</span></a><nav><a href="#top">الرئيسية</a><a href="#group">المجموعة</a><a href="#business">شركاتنا</a><a href="#products">منتجاتنا</a><a href="#projects">مشاريعنا</a><a href="#contact">الاستثمار والشراكات</a><a href="#development">معرفة وأثر</a></nav><a className="cta" href="#contact">تواصل معنا ←</a></header>
<section id="top" className="hero approvedHero"><div className="heroImage"/><div className="veil"/><div className="heroCopy"><span>مجموعة أعمال متكاملة</span><h1>اراك القابضة</h1><h2>صناعة · تجارة · مشاريع · معرفة · تنمية</h2><p>كيانات متخصصة وقدرات متكاملة لخدمة التنمية والاقتصاد والمجتمعات، بأعمال تشغيلية ومنتجات ومشاريع نوعية داخل المملكة وخارجها.</p><div><a className="cta" href="#business">اكتشف المجموعة ←</a></div></div><section className="heroMetrics"><div><b>300+</b><span>موظف وموظفة</span></div><div><b>53</b><span>دولة خبرة ونشاط</span></div><div><b>300 <small>طن/شهر</small></b><span>الطاقة الإنتاجية الحالية</span></div><div><b>40+</b><span>مشروع منجز وقيد التنفيذ</span></div><div><b>100+</b><span>شريك محلي ودولي</span></div><div><b>17%</b><span>نمو أعمال المجموعة</span></div></section></section>
<section className="sectorIntro"><div><span>قطاعاتنا</span><h2>أعمال المجموعة</h2></div><p>مجموعة من الشركات والمؤسسات تعمل في قطاعات متكاملة، وتقدم منتجات وخدمات ومشاريع نوعية في المملكة وخارجها.</p></section>
<section id="business" className="section sectorCards"><header className="sectionHead"><div><span>01 · WHAT WE DO TODAY</span><h2>أعمال اراك اليوم</h2></div><p>قطاعات تشغيل قائمة تخدم السوق عبر التصنيع والتوريد والمقاولات والتنمية والتعليم.</p></header><div className="business">{business.map((x,i)=><article key={x[0]}><div className={'visual v'+i}><small>{x[2]}</small></div><div className="copy"><span>{x[0]} · {x[1]}</span><h3>{x[3]}</h3><p>{x[4]}</p><a href={x[5]} target="_blank">الدخول إلى النشاط ↗</a></div></article>)}</div></section>
<section id="projects" className="projectAnchor"></section><section id="products" className="products section"><header className="sectionHead"><div><span>02 · PRODUCTS</span><h2>توريد متكامل<br/>لمتطلبات المشاريع.</h2></div><p>حلول مواد البناء والديكور والعوازل التي تعرضها اراك التجارية لعملائها.</p></header><div className="productGrid">{products.map((p,i)=><article key={p[0]}><div className={'art a'+i}><i>0{i+1}</i></div><span>{p[1]}</span><h3>{p[0]}</h3><a href="https://araak.net/" target="_blank">التفاصيل ↗</a></article>)}</div></section>
<section className="factory"><div className="factoryArt"><i/><i/></div><div><span>03 · ARAAK STEEL FACTORY</span><h2>صناعةٌ تدخل<br/>في صميم البناء.</h2><p>مصنع اراك للحديد متخصص في تصنيع قطاعات الصلب والصفائح واللفائف وقواطع الحوائط الجافة وإكسسوارات الأسقف الفولاذية، مع مركز لخدمة الصلب.</p><div className="chips"><b>Galvanized Steel</b><b>Drywall Profiles</b><b>Ceiling Accessories</b><b>Steel Service Center</b></div><a href="https://araak.net/اراك-مصنع-اراك-للحديد/" target="_blank">اكتشف المصنع ↗</a></div></section>
<section id="development" className="section"><header className="sectionHead"><div><span>04 · ARAAK DEVELOPMENT</span><h2>خبرة بدأت بالإنسان.</h2></div><p>التعليم والتدريب والاستشارات هي الجذور التي انطلقت منها اراك، ومنها تشكل رصيد من البرامج والمبادرات وبناء القدرات.</p></header><div className="dev"><div><h3>نبني القدرة،<br/>ثم نتركها تعمل.</h3><p>تقييم القدرات المؤسسية، التخطيط الاستراتيجي، الأطر التشغيلية، الجودة والتحسين، دراسات الجدوى وتمكين رواد الأعمال.</p><a href="https://www.araak.org/home/" target="_blank">زيارة اراك للتنمية ↗</a></div><div className="projectList">{projects.map((x,i)=><p key={x}><b>0{i+1}</b>{x}</p>)}</div></div></section>
<section id="academy" className="academy"><div><span>05 · ARAAK ACADEMY</span><h2>المعرفة<br/>كمنتجٍ قابل للنمو.</h2><p>منصة تعليمية تفاعلية تقدم دورات وبرامج تدريبية بمستويات متعددة، مع مواد مسجلة وبث مباشر وأدوات للقياس والتمكين.</p><div className="stats"><b>26 <small>نتيجة بالدورات</small></b><b>20 <small>دورة تدريبية</small></b></div><a href="https://academy.araak.org/" target="_blank">الدخول إلى الأكاديمية ↗</a></div><div className="courses"><small>نماذج من المحتوى الحالي</small>{['الإدارة الذكية للموارد البشرية','إدارة الجودة الشاملة','التخطيط الإداري','بناء فريق العمل','إدارة التغيير','مراقي الحرمين · تدريب المدربين'].map(x=><h3 key={x}>{x}</h3>)}</div></section>
<section id="group" className="section group"><header className="sectionHead"><div><span>06 · THE GROUP</span><h2>اراك ليست نشاطًا واحدًا.</h2></div><p>نجمع واجهات الأعمال القائمة تحت مظلة واحدة، مع إبقاء كل نشاط قريبًا من سوقه وعملائه.</p></header><div className="groupGrid"><a href="https://araak.net/" target="_blank"><b>اراك التجارية</b><span>صناعة · تجارة · مقاولات</span></a><a href="https://www.araak.org/home/" target="_blank"><b>اراك للتنمية</b><span>تعليم · تدريب · استشارات</span></a><a href="https://academy.araak.org/" target="_blank"><b>أكاديمية اراك</b><span>تعليم وتدريب إلكتروني</span></a><div><b>اراك ستورز</b><span>التجارة والمتاجر</span></div></div></section>
<section className="footprint"><div><span>07 · FOOTPRINT</span><h2>حضور محلي.<br/>شبكة دولية.</h2><p>تنطلق اراك من جدة، وتمتد شبكة أعمالها وعلاقاتها عبر أسواق وشراكات دولية.</p></div><div className="saudiMap" aria-label="خريطة المملكة العربية السعودية وموقع جدة"><svg viewBox="0 0 620 620" role="img" aria-hidden="true"><path className="kingdomShape" d="M137 92 L226 71 L295 96 L350 88 L407 118 L474 119 L512 159 L506 207 L542 253 L516 301 L535 353 L493 387 L473 449 L423 478 L390 527 L328 535 L283 507 L221 513 L182 474 L137 451 L119 400 L84 365 L96 311 L72 268 L103 223 L95 174 L125 140 Z"/><circle className="jeddahPulse" cx="112" cy="330" r="18"/><circle className="jeddahDot" cx="112" cy="330" r="6"/><path className="networkLine n1" d="M112 330 Q240 210 445 155"/><path className="networkLine n2" d="M112 330 Q260 340 492 300"/><path className="networkLine n3" d="M112 330 Q230 450 390 500"/></svg><div className="jeddahLabel"><b>جدة</b><span>منطلق اراك</span></div><div className="mapCaption">KINGDOM OF SAUDI ARABIA</div></div></section>
<section id="contact" className="contact"><div><span>08 · BUSINESS ENQUIRIES</span><h2>ماذا تحتاج<br/>من اراك؟</h2><p>منتجات وتوريد ومشاريع وتدريب واستشارات وشراكات عبر نقطة اتصال موحدة.</p></div><form onSubmit={submit}><input name="name" required placeholder="الاسم / الجهة"/><input name="email" type="email" required placeholder="البريد الإلكتروني"/><select name="interest" defaultValue=""><option value="" disabled>اختر نوع الاحتياج</option><option>منتجات ومواد بناء</option><option>مصنع اراك للحديد</option><option>مقاولات ومشاريع</option><option>تدريب وتعليم</option><option>استشارات وتنمية</option><option>شراكة</option></select><textarea name="message" required placeholder="صف احتياجك باختصار"/><button>{sent?'تم استلام طلبك ✓':'إرسال الطلب'}</button></form></section>
<footer><a className="brand" href="#top"><b>اراك</b><span>ARAAK GROUP</span></a><p>نحو توطين القيم لتمكين التنمية.</p></footer>
</main>}